### ISSUE TITLE
Custom Request/Response class

### ISSUE THREAD

**Issue by zakuro9715** [c-bata/kobin#38]
Now, kobin always uses `kobin.environs.request` as a request. So we can use only `LocalRequest`.

Similarly, We can use only `LocalResponse` as a response.

However, I want to use a custom request/response like this:

```python
import yaml
from kobin import Kobin
from kobin.environs import LocalRequest
from .environs import MyRequest, MyResponse

app = Kobin()
app.config['REQUEST_CLASS'] = MyRequest
app.config['RESPONSE_CLASS'] = MyResponse
```

NOTE: It's a just idea. Probably, there are better ways.

**Comment by c-bata** [comment]
@zakuro9715 Thanks for your proposal. But I think this proposal is not agreeable.

When developing the library or plugin for Kobin, the differences of request and response object become an obstacle. If kobin's users are not satisfied with kobin's default request and response object, We need to improve that.

So If you have proposals about request and response object, please submit issues. I'm gonna consider those.

**Comment by zakuro9715** [comment]
OK, thanks for consideration.
